version: 2.1
description: Run drupal-check

commands:
  setup-drupal-check:
    parameters:
      directory:
        type: string
    steps:
      - run:
          name: Setup drupal-check
          working_directory: << parameters.directory >>
          command: |-
            DRUPAL_CHECK=/tmp/drupal-check
            if [ ! -x /tmp/drupal-check ]; then
              curl --fail --silent --output /tmp/drupal-check -O -L https://github.com/mglaman/drupal-check/releases/latest/download/drupal-check.phar
              chmod +x /tmp/drupal-check
            fi

            mkdir -p /tmp/results/analysis/analysis /tmp/results/deprecations/deprecations

            sudo -E apt update
            sudo -E apt install --yes libpng-dev
            sudo -E docker-php-ext-install gd

            # If a composer.drupal-check.json exists merge it into composer.json
            if [[ -r composer.json && -r composer.drupal-check.json ]]; then
              mv composer.json composer.orig.json
              jq -s '.[0] * .[1]' composer.orig.json composer.drupal-check.json > composer.json
            fi

            if [[ -r composer.json ]]; then
              composer install -n --prefer-dist
            fi
  analysis:
    parameters:
      directory:
        type: string
      paths:
        type: string
    steps:
      - run:
          name: "Analysis check"
          environment:
            COMMAND: analysis
          working_directory: << parameters.directory >>
          command: |-
            /tmp/drupal-check --analysis --format=junit --no-progress --no-interaction -- << parameters.paths >> > /tmp/results/analysis/analysis/drupal-check.xml
          when: always
      - store_test_results:
          path: /tmp/results/analysis
          destination: "Drupal Check/analysis"

  deprecations:
    parameters:
      directory:
        type: string
      paths:
        type: string
    steps:
      - run:
          name: "Deprecation check"
          environment:
            COMMAND: deprecations
          working_directory: << parameters.directory >>
          command: |-
            /tmp/drupal-check --deprecations --format=junit --no-progress --no-interaction -- << parameters.paths >> > /tmp/results/deprecations/deprecations/drupal-check.xml
          when: always
      - store_test_results:
          path: /tmp/results/deprecations
          destination: "Drupal Check/deprecations"

executors:
  php-cli:
    docker:
      - image: circleci/php:7.2-cli-node

jobs:
  drupal-check:
    executor: php-cli
    parameters:
      directory:
        type: string
        default: .
      setup:
        description: Steps to perform before running drupal-check
        type: steps
        default: []
      paths:
        type: string
        default: web/modules/custom/ web/themes/custom/
    steps:
      - checkout
      - setup-drupal-check:
          directory: << parameters.directory >>
      - << parameters.setup >>
      - analysis:
          paths: << parameters.paths >>
          directory: << parameters.directory >>
      - deprecations:
          paths: << parameters.paths >>
          directory: << parameters.directory >>
